Repository google/glog, pull requests merged in 2018-06, with the labels that each got.

#318 rename GFLAGS_NAMESPACE to GLOG_GFLAGS_NAMESPACE
  cmake/DetermineGflagsNamespace.cmake
Labels: LGTM, cla: yes

#324 Fix mingw cross compile
  CMakeLists.txt
  src/config.h.cmake.in
  src/demangle.cc
  src/logging.cc
  src/symbolize.cc
  src/windows/port.cc
  src/windows/port.h
Labels: cla: yes

#332 tests: fix compilation with C++17
  src/googletest.h
Labels: cla: yes

#331 Fix windows logging ut
  src/googletest.h
  src/logging_unittest.cc
  src/logging_unittest.err
  src/windows/port.h
Labels: cla: no
