Repository google/glog, pull requests merged in 2019-11, with the labels that each got.

#432 Add support for automatic removal of old logs
  AUTHORS
  CONTRIBUTORS
  src/glog/logging.h.in
  src/logging.cc
  src/windows/dirent.h
  src/windows/glog/logging.h
Labels: cla: yes

#482 Revert "Added fixed log name support"
  src/glog/logging.h.in
  src/logging.cc
  src/logging_unittest.cc
Labels: cla: yes

#483 Support pkg-config
  CMakeLists.txt
Labels: LGTM, cla: yes

#484 removed executable flag from .cmake file
  cmake/DetermineGflagsNamespace.cmake
Labels: cla: yes

#477 src/utilities: fix build without pthread
  src/utilities.cc
  src/utilities.h
Labels: LGTM, cla: yes

#485 src/symbolize.cc: do not check for HAVE_DLFCN_H for macOS
  src/symbolize.cc
Labels: cla: yes

#487 src/logging.cc: fix wrong assignment
  src/logging.cc
Labels: cla: yes

#491 doc: add information about log cleaner
  doc/glog.html
Labels: cla: yes

#489 Added fixed log name support, take 2
  CMakeLists.txt
  Makefile.am
  src/config.h.cmake.in
  src/glog/logging.h.in
  src/logging.cc
  src/logging_unittest.cc
Labels: cla: yes

#368 Use libunwind as an imported target
  .gitignore
  CMakeLists.txt
  cmake/FindUnwind.cmake
  cmake/GetCacheVariables.cmake
  cmake/TestInitPackageConfig.cmake
  cmake/TestPackageConfig.cmake
  glog-config.cmake.in
  glog-modules.cmake.in
  src/package_config_unittest/working_config/CMakeLists.txt
  src/package_config_unittest/working_config/glog_package_config.cc
  src/stacktrace_windows-inl.h
Labels: LGTM, cla: yes, enhancement

#499 Address review comments for Bazel/Win32 build
  bazel/glog.bzl
Labels: cla: yes
