Repository google/glog, pull requests merged in 2021-02, with the labels that each got.

#608 Make stl_logging_unittest more robust.
  src/stl_logging_unittest.cc
Labels: cla: yes

#593 src/logging.cc: Fix a typo in comment
  src/logging.cc
Labels: cla: yes

#592 src/logging.cc: Make LogCleaner aware of filename extension (#589)
  src/logging.cc
Labels: cla: yes

#263 Annotate LOG_EVERY_N macros as a benign race for TSAN
  src/glog/logging.h.in
Labels: cla: yes, enhancement

#400 Fix logmailer problem for dynamic lib use of glog.
  src/logging.cc
Labels: cla: yes

#600 Fix the symlink creation bug if using bazel
  bazel/glog.bzl
Labels: cla: yes

#609 cmake: handle empty unwind version patch component
  cmake/FindUnwind.cmake
Labels: cla: yes

#611 replaced __CYGWIN32__ and __CYGWIN64__ by __CYGWIN__
  src/base/mutex.h
Labels: cla: yes

#492 Fix race conditions in LOG_EVERY_N
  CMakeLists.txt
  src/config.h.cmake.in
  src/glog/logging.h.in
Labels: cla: yes

#610 consolidate readme
  README.rst
  README.windows
Labels: cla: yes

#613 cmake: fixed unwind patch component match check
  cmake/FindUnwind.cmake
Labels: bug, cla: yes
