Repository google/glog, pull requests merged in 2021-07, with the labels that each got.

#677 Remove ubuntu1604 from presubmit.yml
  .bazelci/presubmit.yml
Labels: cla: yes

#676 bazel: add GLOG_CUSTOM_PREFIX_SUPPORT
  bazel/glog.bzl
Labels: cla: yes

#669 log messages periodically (time-based)
  AUTHORS
  CMakeLists.txt
  CONTRIBUTORS
  README.rst
  bazel/glog.bzl
  src/config.h.cmake.in
  src/glog/logging.h.in
  src/googletest.h
  src/logging_unittest.cc
Labels: cla: yes

#686 ci: support more targets
  .github/workflows/macos-builds.yml
  .github/workflows/windows-builds.yml
  CMakeLists.txt
  README.rst
  cmake/GetCacheVariables.cmake
  src/glog/logging.h.in
  src/glog/stl_logging.h.in
  src/glog/vlog_is_on.h.in
  src/logging.cc
  src/logging_unittest.cc
  src/utilities.cc
Labels: cla: yes, enhancement

#684 cmake: prefer linking against gflags::gflags (fixes #683)
  CMakeLists.txt
Labels: cla: yes, enhancement

#685 Fix syscall deprecation warning on macOS >= 10.12
  CMakeLists.txt
  src/config.h.cmake.in
  src/raw_logging.cc
  src/utilities.cc
Labels: cla: yes

#687 fixed exception specification mismatch
  src/googletest.h
Labels: bug, cla: yes

#674 readme: fix wrong header id
  README.rst
Labels: cla: yes

#688 eliminate warnings
  .github/workflows/macos-builds.yml
  .github/workflows/windows-builds.yml
  CMakeLists.txt
  src/demangle.cc
  src/demangle.h
  src/glog/logging.h.in
  src/glog/raw_logging.h.in
  src/googletest.h
  src/logging.cc
  src/logging_unittest.cc
  src/raw_logging.cc
  src/signalhandler.cc
  src/signalhandler_unittest.cc
  src/stacktrace_unittest.cc
  src/stacktrace_windows-inl.h
  src/stl_logging_unittest.cc
  src/symbolize.cc
  src/symbolize.h
  src/symbolize_unittest.cc
  src/utilities.cc
  src/vlog_is_on.cc
Labels: cla: yes
