Repository google/glog, pull requests merged in 2021-12, with the labels that each got.

#737 ci: reworked windows builds
  .github/workflows/android.yml
  .github/workflows/coveralls.yml
  .github/workflows/linux-builds.yml
  .github/workflows/linux.yml
  .github/workflows/macos-builds.yml
  .github/workflows/macos.yml
  .github/workflows/windows-builds.yml
  .github/workflows/windows.yml
  CMakeLists.txt
  README.rst
  src/config.h.cmake.in
  src/demangle.cc
  src/demangle_unittest.cc
  src/glog/logging.h.in
  src/googletest.h
  src/logging_custom_prefix_unittest.cc
  src/logging_unittest.cc
  src/mock-log_unittest.cc
  src/symbolize_unittest.cc
  src/utilities.cc
Labels: bug, cla: yes

#751 cmake: set CMP0074 policy
  .github/workflows/android.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
  CMakeLists.txt
Labels: cla: yes

#727 Added gmtoff() method in 'LogMessageTime' to get GMT offset
  AUTHORS
  CONTRIBUTORS
  src/glog/logging.h.in
  src/logging.cc
  src/logging_custom_prefix_unittest.cc
  src/logging_unittest.cc
  src/mock-log.h
Labels: cla: yes

#754 LogCleaner: Fix relative paths and add a new test
  CMakeLists.txt
  cmake/RunCleanerTest3.cmake
  src/cleanup_with_absolute_prefix_unittest.cc
  src/cleanup_with_relative_prefix_unittest.cc
  src/logging.cc
Labels: bug

#757 eliminate msvc warnings
  .github/workflows/windows.yml
  src/glog/logging.h.in
Labels: bug

#758 cmake: require at least version 3.16
  CMakeLists.txt
  README.rst
  src/package_config_unittest/working_config/CMakeLists.txt
Labels: enhancement

#759 ci: enable warnings as errors
  .github/workflows/android.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
  src/symbolize.cc
Labels: enhancement

#760 LogCleaner: make `overdue_days_` unsigned int
  src/glog/logging.h.in
  src/logging.cc
Labels: enhancement

#763 provide backward compatible send overload
  bazel/glog.bzl
  src/glog/logging.h.in
  src/logging.cc
  src/utilities.h
Labels: bug

#765 run clang-tidy
  .clang-format
  .clang-tidy
  src/demangle.cc
  src/googletest.h
  src/logging.cc
  src/logging_unittest.cc
  src/signalhandler.cc
  src/signalhandler_unittest.cc
  src/stacktrace_generic-inl.h
  src/stacktrace_libunwind-inl.h
  src/stacktrace_powerpc-inl.h
  src/stacktrace_unittest.cc
  src/stacktrace_x86-inl.h
  src/stacktrace_x86_64-inl.h
  src/symbolize.cc
  src/symbolize_unittest.cc
  src/vlog_is_on.cc
Labels: enhancement

#766 eliminate clang warnings
  .github/workflows/android.yml
  .github/workflows/linux.yml
  .github/workflows/macos.yml
  .github/workflows/windows.yml
  CMakeLists.txt
  src/logging_custom_prefix_unittest.cc
  src/logging_unittest.cc
  src/raw_logging.cc
  src/symbolize_unittest.cc
Labels: enhancement

#767 ensure `_Unwind_Backtrace` to actually be available
  CMakeLists.txt
  bazel/glog.bzl
  src/config.h.cmake.in
  src/stacktrace_unwind-inl.h
  src/utilities.h
Labels: bug

#770 revert to signed int atomics
  src/glog/logging.h.in
  src/logging.cc
Labels: bug

#771 Add the "FLAG_log_year_in_prefix"
  src/glog/logging.h.in
  src/logging.cc
Labels: enhancement

#773 use uint32 for --max-log-size
  src/base/commandlineflags.h
  src/glog/logging.h.in
  src/logging.cc
  src/logging_custom_prefix_unittest.cc
  src/logging_unittest.cc
Labels: enhancement

#775 stdcxx: eliminate excessive use of std::string::c_str()
  src/googletest.h
  src/logging.cc
Labels: enhancement
