Repository google/glog, pull requests merged in 2021-05, with the labels that each got.

#646 release 0.5
  ChangeLog
Labels: cla: yes

#651 Expose `IsGoogleLoggingInitialized()` in public API.
  src/glog/logging.h.in
  src/logging_custom_prefix_unittest.cc
  src/logging_unittest.cc
  src/utilities.cc
  src/utilities.h
Labels: cla: yes, enhancement

#656 Fix cmake configuration for cygwin environment
  CMakeLists.txt
Labels: cla: yes

#650 Allow updating vmodule levels after vmodule level has been cached
  src/glog/vlog_is_on.h.in
  src/logging_unittest.cc
  src/vlog_is_on.cc
Labels: bug, cla: yes
