Repository google/glog, pull requests merged in 2021-03, with the labels that each got.

#614 Rename BUILD to BUILD.bazel.
  BUILD.bazel
  bazel/example/BUILD.bazel
  bazel/glog.bzl
Labels: cla: yes

#619 cmake: export symbols selectively
  CMakeLists.txt
  src/glog/logging.h.in
  src/symbolize.h
Labels: cla: yes

#622 handle --max_log_size overflow
  src/logging.cc
Labels: bug, cla: yes

#624 fully qualify std::string
  src/glog/logging.h.in
Labels: bug, cla: yes

#627 cmake: do not require a C compiler
  CMakeLists.txt
Labels: cla: yes, enhancement

#626 use C++ headers
  CMakeLists.txt
  src/base/commandlineflags.h
  src/base/mutex.h
  src/config.h.cmake.in
  src/demangle.cc
  src/glog/logging.h.in
  src/glog/raw_logging.h.in
  src/glog/vlog_is_on.h.in
  src/logging.cc
  src/logging_striptest_main.cc
  src/logging_unittest.cc
  src/raw_logging.cc
  src/signalhandler.cc
  src/signalhandler_unittest.cc
  src/stacktrace_powerpc-inl.h
  src/stacktrace_unittest.cc
  src/stacktrace_x86-inl.h
  src/stacktrace_x86_64-inl.h
  src/symbolize.cc
  src/symbolize_unittest.cc
  src/utilities.cc
  src/vlog_is_on.cc
  src/windows/dirent.h
  src/windows/port.cc
  src/windows/port.h
Labels: cla: yes, enhancement

#595 Change counter type to uint64
  src/glog/logging.h.in
  src/logging.cc
  src/windows/glog/logging.h
Labels: cla: yes

#623 document C++ version
  README.rst
Labels: cla: yes, enhancement

#618 build: set ac_cv___attribute___printf_4_5
  CMakeLists.txt
  bazel/glog.bzl
Labels: bug, cla: yes

#628 bazel: use expand_template instead of genrules
  bazel/glog.bzl
Labels: cla: yes
