Repository google/glog, pull requests merged in 2021-04, with the labels that each got.

#632 cmake: build shared libs by default
  CMakeLists.txt
Labels: cla: yes

#631 fixed file extension
  src/logging.cc
Labels: cla: yes

#635 Use generated config.h for Windows.
  bazel/glog.bzl
Labels: cla: yes

#625 removed windows-specific headers
  src/windows/glog/log_severity.h
  src/windows/glog/logging.h
  src/windows/glog/raw_logging.h
  src/windows/glog/stl_logging.h
  src/windows/glog/vlog_is_on.h
Labels: cla: yes, enhancement

#638 Add Windows builds using GitHub Actions
  .github/workflows/windows-builds.yml
Labels: cla: yes

#639 fixed windows builds
  CMakeLists.txt
  README.rst
  bazel/glog.bzl
  cmake/GetCacheVariables.cmake
  cmake/TestInitPackageConfig.cmake
  cmake/TestPackageConfig.cmake
  src/config_for_unittests.h
  src/logging_unittest.cc
  src/package_config_unittest/working_config/CMakeLists.txt
  src/windows/config.h
  src/windows/port.h
Labels: bug, cla: yes

#620 cmake: allow to disable symbolize
  CMakeLists.txt
  src/utilities.h
Labels: bug, cla: yes

#554 Add support for customizing the prefix format
  CMakeLists.txt
  README.rst
  src/glog/logging.h.in
  src/logging.cc
  src/logging_custom_prefix_unittest.cc
  src/logging_custom_prefix_unittest.err
Labels: cla: yes, enhancement

#640 fix gflags windows linker warnings
  CMakeLists.txt
  src/glog/logging.h.in
  src/logging_custom_prefix_unittest.cc
Labels: bug, cla: yes

#637 fix LogCleaner::IsLogFromCurrentProject for filename_extension
  src/logging.cc
Labels: bug, cla: yes

#641 CHECK support for nullptr (fixes #341)
  CMakeLists.txt
  CONTRIBUTORS
  bazel/glog.bzl
  src/config.h.cmake.in
  src/glog/logging.h.in
  src/logging.cc
Labels: cla: yes, enhancement

#642 readme: update CMake source directory option
  README.rst
Labels: cla: yes
